global:
  scrape_interval: 5s # Cek target setiap 5 detik

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    # Prometheus akan mengambil metrik yang dikirim Caliper dari Pushgateway
    static_configs:
      - targets: ["caliper_pushgateway:9091"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
