apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: caliper-prometheus
    url: http://caliper_prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 5s
    editable: false
