test:
  name: set-get-benchmark
  description: A benchmark for the simple-storage contract.
  workers:
    number: 1
  rounds:
    - label: set-value
      description: Write a value to the storage contract.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
        module: benchmarks/workload/write-read.js
        arguments:
          operation: set
    - label: get-value
      description: Read a value from the storage contract.
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
        module: benchmarks/workload/write-read.js
        arguments:
          operation: get
